<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pathology</name>
   <tag></tag>
   <elementGuidId>3370fccd-973a-441d-b0b2-05d38e6af3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-app</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-collapse']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df1909a8-f6ae-43ad-a40f-c55b849085a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-app</value>
      <webElementGuid>f67705d8-cef4-42a4-b110-54445c044583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hospitalb.com/reports/diagnostic-pathology-test-report</value>
      <webElementGuid>9db8b4fc-d5b2-427e-95be-b51a5e7abe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Pathology
                            </value>
      <webElementGuid>3cec645f-2c3c-4111-966c-970e88c2157b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-collapse&quot;)/ul[@class=&quot;nav navbar-nav&quot;]/li[1]/a[@class=&quot;btn btn-app&quot;]</value>
      <webElementGuid>51adfc80-b5eb-4672-94f2-d8fc8e5fb78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-collapse']/ul/li/a</value>
      <webElementGuid>a08da63f-64dc-42c1-9b9d-e72b775d3ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hospitalb.com/reports/diagnostic-pathology-test-report')]</value>
      <webElementGuid>77889c09-be76-4518-8c6c-52a65aedb342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/ul/li/a</value>
      <webElementGuid>f51a8665-d887-485a-bc4d-6e0cb159c4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hospitalb.com/reports/diagnostic-pathology-test-report' and (text() = '
                                
                                Pathology
                            ' or . = '
                                
                                Pathology
                            ')]</value>
      <webElementGuid>b9984c4a-8057-47b2-95e6-ac44905758c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
