<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_user-image</name>
   <tag></tag>
   <elementGuidId>93456ec1-4393-465c-9f6d-05f08df1608e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.user-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='User Image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>128b7937-566f-43bd-a908-bb6707a8527e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hospitalb.com/img/user.png</value>
      <webElementGuid>51e55ebd-dc9c-4f78-b0c0-ac920fe93f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-image</value>
      <webElementGuid>5ac90059-6194-4704-830a-95936b16e3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Image</value>
      <webElementGuid>5184caaa-b9c9-4ef8-9e5b-67ec47ba00e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-blue-light layout-top-nav  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/header[@class=&quot;main-header&quot;]/nav[@class=&quot;navbar navbar-static-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-custom-menu&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown user user-menu&quot;]/a[@class=&quot;dropdown-toggle&quot;]/img[@class=&quot;user-image&quot;]</value>
      <webElementGuid>8fa345f0-bed1-4670-8e08-8c008896629d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Image']</value>
      <webElementGuid>e5fb25ae-0bd2-4168-b5e6-9d29bbd1c429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4dc762bd-0014-48f9-b54a-5b2253a13199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hospitalb.com/img/user.png' and @alt = 'User Image']</value>
      <webElementGuid>1cd2182f-df9e-42bc-95df-334c61b4b27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
