<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mother_name</name>
   <tag></tag>
   <elementGuidId>e8ce682f-8f9b-4804-888f-5b71112f24e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mother_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mother_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26133bea-ffc1-4f0a-ba74-5d286b5c356c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0e44733-4dda-4b23-9c35-e25d70a06caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>89587755-0f1d-4191-9802-9dbe56ef868f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mother_name</value>
      <webElementGuid>8dceb3c5-978d-4b19-ad6f-b2f69d51f0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mother_name</value>
      <webElementGuid>57827317-bebb-49f1-8b3c-4f8802c62ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Mother Name</value>
      <webElementGuid>e042edc8-059b-4ed5-ad21-a5e0072a70c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mother_name&quot;)</value>
      <webElementGuid>87dd2e2c-2777-4e09-9817-834462e5a9c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mother_name']</value>
      <webElementGuid>049895cd-6313-4615-ab15-b555aa38b217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div[2]/div/div[2]/input</value>
      <webElementGuid>5808f7d9-491f-40b5-8ff7-4d01f38175b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>3385bfbc-5218-488e-a7dd-9081bfc8960a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mother_name' and @id = 'mother_name' and @placeholder = 'Write your Mother Name']</value>
      <webElementGuid>437c633b-cc81-461d-8163-c6981b37117f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
