<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_from</name>
   <tag></tag>
   <elementGuidId>29170bbd-dab6-4919-9d2f-37c20da24122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eda33ee5-1873-49e9-9fc3-3ab759b42258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker</value>
      <webElementGuid>0b3a9dbc-a37e-4f2a-b3a5-ce011e837776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>467ae789-bd7e-44d7-a137-077f8860bae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c1eec45-2e98-47fc-9142-360598d62f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from</value>
      <webElementGuid>36eb3932-7cc8-44a6-9170-6ed1393bf3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from</value>
      <webElementGuid>600760d2-788a-4bc7-8ddd-2fe63e16d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from&quot;)</value>
      <webElementGuid>fe83f68e-63a4-418b-b5e4-7e67aefe39ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from']</value>
      <webElementGuid>2b0098d8-009c-4907-b98d-96326ea1ac53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='custom_search_form']/div/div/div/div/input[2]</value>
      <webElementGuid>338c3325-f6e3-4bdd-953c-f02eebf9ae0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>4ec18eb5-3655-47c6-b017-a5e04f94e8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'from' and @id = 'from']</value>
      <webElementGuid>f61aaa49-803a-4ed8-8e0e-8a17a59c8dbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
