<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_father_name</name>
   <tag></tag>
   <elementGuidId>7e50eec0-7c9b-480e-889f-fb346f42d0c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#father_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='father_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6203d249-8ab8-407c-b577-9247951d703e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ae2352c-d2d3-4f72-b71d-618e06550d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e41f6b47-dfc2-4128-9570-b686ea7dfb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>father_name</value>
      <webElementGuid>97f0afe8-02a6-40a8-aa9a-b13296b9219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>father_name</value>
      <webElementGuid>3db6e34c-e5f7-4692-bce2-066e05d0ce89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Father Name</value>
      <webElementGuid>670db37f-1877-4153-a7c4-c39b7c563e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;father_name&quot;)</value>
      <webElementGuid>1fdf150f-d8a1-4728-b7e8-46a8090d4e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='father_name']</value>
      <webElementGuid>c3d0d671-22f6-428f-8c56-5127ef0f484f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div[2]/div/div/input</value>
      <webElementGuid>ddd3764b-12c9-4563-a817-662c26c0e4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a4fc61a4-3651-47ce-9b18-be9f719cafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'father_name' and @id = 'father_name' and @placeholder = 'Write your Father Name']</value>
      <webElementGuid>ca52ea48-3102-455d-a52f-578afc7eca9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
