<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_full_name</name>
   <tag></tag>
   <elementGuidId>cbda9a5c-9d23-40da-b75c-a267b5874db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#full_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='full_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>287c8ba7-3337-4b91-8fca-4ef2f735e0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e14996e6-4231-419a-b064-c6ed005c6645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>399ad7f0-58c8-4a0b-b9d6-5587182d44c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>3947f723-6c26-4152-ad7e-7627537797de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radiologist</value>
      <webElementGuid>69d2dcd8-ee26-470b-922f-b92507a40297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>df648176-7271-4414-bdcb-68521bf7ef46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Full Name</value>
      <webElementGuid>60a38069-74ec-461a-ab7b-b8ec5f47b4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full_name&quot;)</value>
      <webElementGuid>14c274d9-8ea3-4e8f-8504-22fb18ac16e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='full_name']</value>
      <webElementGuid>717e4ca4-7b6b-44f6-a5ff-421fa1412452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div/div/div/input</value>
      <webElementGuid>afa64385-65e9-4417-9f71-67decfa53124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>0acc7fe4-2a7c-4933-82a7-f8944fecba62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full_name' and @id = 'full_name' and @placeholder = 'Write your Full Name']</value>
      <webElementGuid>272ed497-8bab-441e-97f2-74bfd0c8f035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmail3']</value>
      <webElementGuid>10fcf6d0-e1eb-4ea6-877a-44c511836098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div/div/input</value>
      <webElementGuid>d409ffde-db65-4b57-8ea5-725d2572aa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c6090bf7-7931-4240-a1c7-2a098231d09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full_name' and @id = 'inputEmail3' and @placeholder = 'Name']</value>
      <webElementGuid>76f6b51e-010f-4323-adf0-35d2588d0aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
