<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_full_name</name>
   <tag></tag>
   <elementGuidId>cbda9a5c-9d23-40da-b75c-a267b5874db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmail3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmail3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5961b065-d2af-41f8-8854-15aa8fc495f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ef32756-01c2-41e7-a480-b58471136a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>fd2e8c12-fe4b-4d66-9e29-81e9ff23ac6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full_name</value>
      <webElementGuid>21a5d323-7bd8-40f4-950e-dd2029850c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pathologist</value>
      <webElementGuid>b2b096a7-4ab9-4ca8-8709-9e8bb95434fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmail3</value>
      <webElementGuid>0ced30c3-f8ec-4241-a83b-78902c430219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>440b9d32-04f2-4120-b045-9758b1a7bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myForm&quot;)/div[@class=&quot;box-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/input[@id=&quot;inputEmail3&quot;]</value>
      <webElementGuid>89b924db-da83-4191-89e6-a1e296a5e4ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmail3']</value>
      <webElementGuid>a5a458f6-d703-4e6c-9812-ad9a5c31cac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div/div/input</value>
      <webElementGuid>747d4350-6327-48d8-8035-2f6b03d8414c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7d63aaa9-6b8b-4dc2-b95d-fb5ebb66800b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full_name' and @id = 'inputEmail3' and @placeholder = 'Name']</value>
      <webElementGuid>45b5ec2c-47af-4ae4-b63a-66eda9af4504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
