<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Profile Image</name>
   <tag></tag>
   <elementGuidId>d854ad30-93ae-4b7a-95d4-704e629710ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='myForm']/div/div[7]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>452968c8-1187-4ba4-b139-140472c6fdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4</value>
      <webElementGuid>39a1ae5f-d3df-4629-ba7b-78cdda60a522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Profile Image</value>
      <webElementGuid>d482e4a3-7c0c-4eef-ad13-1e41be183344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myForm&quot;)/div[@class=&quot;box-body&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;col-md-4&quot;]</value>
      <webElementGuid>404b7271-72c0-43ec-98ee-a0ce124a757b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='myForm']/div/div[7]/label</value>
      <webElementGuid>c649bc45-6479-44a6-bd81-6cd76c6a9248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label</value>
      <webElementGuid>ab534262-4d2f-468f-bbb3-f5910d2cf8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Profile Image' or . = ' Profile Image')]</value>
      <webElementGuid>c0fddf4c-d885-4ee4-9935-0eee3c3dd630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
