<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please Select Designation</name>
   <tag></tag>
   <elementGuidId>6236b931-9159-4a29-b3d7-ff72cb88c856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-designation-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-designation-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>054f46d7-a568-4211-a36f-f44b83360bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2bc89ff2-c153-4a87-b309-06cfcf4d5427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-designation-container</value>
      <webElementGuid>b735eac8-845a-4c25-aed8-d7853a536a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please Select Designation</value>
      <webElementGuid>83a62fdb-9cb4-4577-8236-671ee77e7760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Designation</value>
      <webElementGuid>47b110ec-95f6-4cff-ab62-d4426e40a62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-designation-container&quot;)</value>
      <webElementGuid>5e01a202-728a-4985-8d99-2fc3d133181c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-designation-container']</value>
      <webElementGuid>e2923a4a-1d9f-4085-bdbc-4511d0d6e480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div[3]/div/div/span/span/span/span</value>
      <webElementGuid>e9e62510-ebe3-48b0-8a3f-8b7619189874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>40bb61e2-679a-4f40-a54a-8e645da939a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-designation-container' and @title = 'Please Select Designation' and (text() = 'Please Select Designation' or . = 'Please Select Designation')]</value>
      <webElementGuid>d1acd3c0-c41c-4631-9727-83bfd24074de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
