<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_permanent_address</name>
   <tag></tag>
   <elementGuidId>235c5b2a-a630-40db-89a1-3b5472385d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permanent_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='permanent_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9e7dfe54-4d5e-4214-a666-53736ccd3236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5f576d8f-385b-431d-85d1-21e0be162eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permanent_address</value>
      <webElementGuid>f12c7871-5e6d-4cd2-bc14-7e6ab3fe4c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanent_address</value>
      <webElementGuid>23731efa-cff4-416c-9f1b-0bcd6e5b604b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>63f314c1-cc9a-4a52-b1b4-b2f2d953ce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Permanent address</value>
      <webElementGuid>4b7bfcb7-b5af-40f5-8ce7-035955d0ff07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permanent_address&quot;)</value>
      <webElementGuid>b8040f56-fad0-45e6-baf6-ccedc601bde1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='permanent_address']</value>
      <webElementGuid>f7a2e9ea-c59e-429a-bd91-b21578357c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-1']/div/div/div[2]/textarea</value>
      <webElementGuid>55a9985e-4e71-4b1b-9767-6b9f6e2e2dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>dbc19640-d4ff-4a2c-838c-0dc8e43a18c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'permanent_address' and @id = 'permanent_address' and @placeholder = 'Write your Permanent address']</value>
      <webElementGuid>ad3649f2-499c-413a-956f-5f07374de535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
