<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_present_address</name>
   <tag></tag>
   <elementGuidId>95ad7b65-e485-4cc9-a991-fca666de2e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#present_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='present_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9a91b2f6-b1e3-447a-85fd-5f0411dfe56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5e1e9a2a-f3f7-4bb9-85be-c6b5c6272ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>present_address</value>
      <webElementGuid>1789fdfb-a2db-490d-ad05-f49994f27d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>present_address</value>
      <webElementGuid>3e3275a0-c624-49f2-89e3-7c50330dc1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>76beae07-be5d-4722-8a07-897d315d63d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your Present address</value>
      <webElementGuid>3e98633c-a03b-4d74-8d8f-9a4136fc12c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;present_address&quot;)</value>
      <webElementGuid>25cf353a-de0d-4068-8c75-c5cd5f0ddcc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='present_address']</value>
      <webElementGuid>b6163026-814e-4188-a286-e3ac0bc351ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-1']/div/div/div/textarea</value>
      <webElementGuid>4c84af64-3223-4b7a-b92b-042c7a015056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/textarea</value>
      <webElementGuid>09dc5e6e-429d-4916-9e47-e60dbc3a4667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'present_address' and @id = 'present_address' and @placeholder = 'Write your Present address']</value>
      <webElementGuid>6b836883-22e1-4a4e-9435-96bb9d6facd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
