<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_select2-selection__rendered</name>
   <tag></tag>
   <elementGuidId>9a812e99-5552-4b74-bb88-164c03d69afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.select2-selection__rendered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-step-0']/div[4]/div/div/span/span/span/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>fa7b06c9-fc82-4e0c-af7e-5f03ade3fc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5b5eaa12-a8a6-4c5b-91ad-492b723d106f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-step-0&quot;)/div[@class=&quot;form-group has-error has-danger&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-sm-4&quot;]/span[@class=&quot;select2 select2-container select2-container--default select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--multiple&quot;]/ul[@class=&quot;select2-selection__rendered&quot;]</value>
      <webElementGuid>7ce7d4fe-8c08-4388-84a1-53a8c44fde4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-step-0']/div[4]/div/div/span/span/span/ul</value>
      <webElementGuid>f936e4c0-b0e6-456f-9d09-27a3382743e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul</value>
      <webElementGuid>9ba69aae-e421-42c5-8925-ba2518b7e1b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
